version: '3'

services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app
      - MYSQL_PASSWORD=!ChangeMe!
      - MYSQL_USER=app

  adminer:
    image: adminer:latest
    ports: 
      - '8777:8080'

  backend:
    image: bitnami/symfony:latest
    depends_on:
      - database
    ports:
      - '8000:8000'
    volumes:
      - './backend:/app'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SYMFONY_PROJECT_NAME=myapp
      - SYMFONY_DATABASE_HOST=database
      - SYMFONY_DATABASE_PORT_NUMBER=3306
      - SYMFONY_DATABASE_USER=app
      - SYMFONY_DATABASE_NAME=app
      - SYMFONY_DATABASE_NAME=!ChangeMe!
      - SYMFONY_PROJECT_SKELETON=symfony/skeleton



  